import { defineConfig } from "vite-plus";
import base from "./vite.config.ts";

// Supported workspace behavior, excluding upstream-only provider and host suites.
export default defineConfig({
  ...base,
  test: {
    ...base.test,
    include: [
      "apps/server/src/orchestration/decider.active-order.test.ts",
      "apps/server/src/orchestration/decider.userInputDismiss.test.ts",
      "apps/server/src/orchestration/decider.settled.test.ts",
      "apps/server/src/orchestration/projector.test.ts",
      "apps/server/src/persistence/Migrations/049_ProjectionThreadsActiveOrderKey.test.ts",
      "apps/server/src/textGeneration/ClaudeTextGeneration.test.ts",
      "apps/server/src/provider/Drivers/ClaudeHome.test.ts",
      "apps/server/src/provider/Layers/ProviderSessionReaper.test.ts",
      "apps/server/src/pullRequest/PullRequestService.coder.test.ts",
      "apps/server/src/provider/Layers/ProviderService.compaction.test.ts",
      "apps/server/src/provider/Layers/ClaudeCapabilitiesProbe.test.ts",
      "apps/server/src/provider/Layers/ClaudeCapabilitiesProbe.timeout.test.ts",
      "apps/server/src/provider/Layers/codexUsageLimits.test.ts",
      "apps/server/src/provider/Layers/claudeUsageLimits.test.ts",
      "apps/server/src/provider/providerUsageLimits.test.ts",
      "apps/server/src/codexModelOptions.test.ts",
      "apps/server/src/provider/Drivers/ClaudeCli.test.ts",
      "apps/server/src/provider/Drivers/CodexHomeLayout.test.ts",
      "apps/server/src/provider/PastedImageAttachments.test.ts",
      "apps/server/src/provider/Layers/ClaudeAdapter.test.ts",
      "apps/server/src/provider/Layers/CodexAdapter.test.ts",
      "apps/server/src/provider/Layers/CodexCollabRuntime.integration.test.ts",
      "apps/server/src/provider/Layers/CodexCollabWire.test.ts",
      "apps/server/src/provider/Layers/CodexIntegrationPolicy.test.ts",
      "apps/server/src/provider/Layers/CodexProvider.test.ts",
      "apps/server/src/provider/Layers/CodexSessionRuntime.test.ts",
      "apps/server/src/provider/Layers/ProviderInstanceRegistryHydration.test.ts",
      "apps/server/src/provider/Layers/codexLaunchArgs.test.ts",
      "apps/server/src/textGeneration/CodexTextGeneration.test.ts",
      "apps/server/src/coderVcsStatus.test.ts",
      "apps/server/src/coderWs.test.ts",
      "apps/server/src/orchestration/Layers/OrchestrationSubscription.test.ts",
      "apps/server/src/serverSettings.persistence.test.ts",
      "apps/server/src/serverSettings.redaction.test.ts",
      "apps/server/src/terminal/NodePtyAdapter.test.ts",
      "apps/server/src/orchestration/Layers/ProviderCommandReactor.test.ts",
      "apps/server/src/orchestration/Layers/ProviderRuntimeIngestion.test.ts",
      "apps/server/src/workspace/*.test.ts",
      "apps/server/src/git/*.test.ts",
      "apps/server/src/vcs/*.test.ts",
      "apps/server/src/sourceControl/*.test.ts",
      "apps/server/src/orchestration/ThreadSettlementPolicy.test.ts",
      "apps/server/src/orchestration/ThreadSettlementReactor.test.ts",
      "apps/server/src/orchestration/ThreadPullRequestReactor.test.ts",
      "apps/server/src/orchestration/Layers/OrchestrationEngine.test.ts",
      "apps/server/src/orchestration/Layers/ProjectionPipeline.test.ts",
      "apps/server/src/persistence/Layers/ProjectionRepositories.test.ts",
      "apps/server/src/persistence/Layers/ProjectionThreadActivities.test.ts",
      "apps/server/src/project/ProjectSetupScriptRunner.test.ts",
      "apps/server/src/orchestration/Layers/CheckpointReactor.test.ts",
      "apps/server/src/orchestration/Layers/ProjectionSnapshotQuery.test.ts",
      "apps/server/src/pathExpansion.test.ts",
    ],
  },
});
