// @effect-diagnostics nodeBuiltinImport:off
import { deepStrictEqual, match, strictEqual, throws } from "node:assert";
import { describe, it } from "node:test";

import { buildCoderScpInvocation, scopeCoderScpConfig } from "./scp.ts";

describe("Coder SCP", () => {
  it("keeps only the randomized Coder host and hardens its ProxyCommand", () => {
    const config = [
      "# generated by Coder",
      "Host t3-coder-1234-*",
      "\tConnectTimeout=0",
      "\tProxyCommand C:/Coder/coder.exe --global-config C:/config ssh --stdio --wait=no --ssh-host-prefix t3-coder-1234- %h",
      "",
      "Host *.coder.example",
      "\tProxyCommand C:/Coder/coder.exe connect %h",
    ].join("\r\n");

    const scoped = scopeCoderScpConfig(config, "t3-coder-1234-");

    match(scoped, /^Host t3-coder-1234-\*/u);
    match(
      scoped,
      /--disable-network-telemetry --disable-direct-connections --no-version-warning ssh --stdio/u,
    );
    strictEqual(scoped.includes("coder.example"), false);
    strictEqual(scoped.includes(" connect "), false);
  });

  it("builds SCP as an argument-array invocation on Windows", () => {
    deepStrictEqual(
      buildCoderScpInvocation({
        platform: "win32",
        sshConfigPath: String.raw`C:\Temp\ssh-config`,
        localPath: String.raw`C:\Temp\image.png`,
        sshHost: "t3-coder-1234-workspace",
        remotePath: ".t3-coder/attachments/1234.png.tmp",
      }),
      {
        executable: "scp.exe",
        args: [
          "-F",
          String.raw`C:\Temp\ssh-config`,
          "-B",
          String.raw`C:\Temp\image.png`,
          "t3-coder-1234-workspace:.t3-coder/attachments/1234.png.tmp",
        ],
      },
    );
  });

  it("rejects arbitrary SCP destinations", () => {
    throws(
      () =>
        buildCoderScpInvocation({
          platform: "win32",
          sshConfigPath: "config",
          localPath: "image.png",
          sshHost: "workspace",
          remotePath: "../../outside.png",
        }),
      /generated T3 Coder transfer path/u,
    );
  });
});
